import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import TopBar from "@/components/topBar";
import BtnLlamadaFlotante from "@/components/btnLlamadaFlotante";

const poppinsLight = localFont({
  src: "./fonts/Poppins-Light.woff2",
  variable: "--font-poppins-light",
  display: "swap",
});

const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.woff2",
  variable: "--font-poppins-regular",
  display: "swap",
});

const poppinsMedium = localFont({
  src: "./fonts/Poppins-Medium.woff2",
  variable: "--font-poppins-medium",
  display: "swap",
});

const poppinsSemibold = localFont({
  src: "./fonts/Poppins-SemiBold.woff2",
  variable: "--font-poppins-semibold",
  display: "swap",
});

const poppinsBold = localFont({
  src: "./fonts/Poppins-Bold.woff2",
  variable: "--font-poppins-bold",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${poppinsLight.variable} ${poppinsRegular.variable} ${poppinsMedium.variable} ${poppinsSemibold.variable} ${poppinsBold.variable} antialiased`}
      >
        <Header />
        {children}
        <BtnLlamadaFlotante />
      </body>
    </html>
  );
}
